// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQtjTXnLNo58WgcQhB0aMEw3BHK5-OBJA',
    appId: '1:1035842800434:web:2e18cfa758a1c6984c652b',
    messagingSenderId: '1035842800434',
    projectId: 'bboxx-leadflow',
    authDomain: 'bboxx-leadflow.firebaseapp.com',
    storageBucket: 'bboxx-leadflow.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZUj3FczLrTNVQNuHUC4cOzoqUi9U1cSE',
    appId: '1:1035842800434:android:f0b489655fae65a24c652b',
    messagingSenderId: '1035842800434',
    projectId: 'bboxx-leadflow',
    storageBucket: 'bboxx-leadflow.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbKE4M8YEpZMvy8PYzMdp3rD0R0AXUxy8',
    appId: '1:1035842800434:ios:84cde033e90b4b204c652b',
    messagingSenderId: '1035842800434',
    projectId: 'bboxx-leadflow',
    storageBucket: 'bboxx-leadflow.appspot.com',
    iosClientId:
        '1035842800434-p8qochevfjive6lddo44t5v7psdbfd8d.apps.googleusercontent.com',
    iosBundleId: 'com.bboxx.leadflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbKE4M8YEpZMvy8PYzMdp3rD0R0AXUxy8',
    appId: '1:1035842800434:ios:68dac34d275552ef4c652b',
    messagingSenderId: '1035842800434',
    projectId: 'bboxx-leadflow',
    storageBucket: 'bboxx-leadflow.appspot.com',
    iosClientId:
        '1035842800434-fqcdj31099jsmf8qgjob9ccs04tphgmc.apps.googleusercontent.com',
    iosBundleId: 'com.bboxx.leadflow.RunnerTests',
  );
}
